In [1]:
import pandas as pd
import openpyxl as xl

In [2]:
df = pd.read_csv("online_retail.csv")

In [3]:
df.shape

(541909, 8)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [5]:
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [6]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [7]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [8]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [9]:
df.isnull().sum().sum()

np.int64(136534)

In [10]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
541904    False
541905    False
541906    False
541907    False
541908    False
Length: 541909, dtype: bool

In [11]:
df.duplicated().sum()

np.int64(5268)

In [12]:
df[df.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
...,...,...,...,...,...,...,...,...
541675,581538,22068,BLACK PIRATE TREASURE CHEST,1,2011-12-09 11:34:00,0.39,14446.0,United Kingdom
541689,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,2011-12-09 11:34:00,2.49,14446.0,United Kingdom
541692,581538,22992,REVOLVER WOODEN RULER,1,2011-12-09 11:34:00,1.95,14446.0,United Kingdom
541699,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom

In [13]:
(df["UnitPrice"] <=0) .sum()

np.int64(2517)

In [14]:
df["InvoiceNo"].astype(str).str.startswith("C").sum()

np.int64(9288)

In [15]:
df["CustomerID"].isnull().sum()

np.int64(135080)

In [16]:
df[df["Description"].isnull()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
535322,581199,84581,NaN,-2,2011-12-07 18:26:00,0.0,NaN,United Kingdom
535326,581203,23406,NaN,15,2011-12-07 18:31:00,0.0,NaN,United Kingdom
535332,581209,21620,NaN,6,2011-12-07 18:35:00,0.0,NaN,United Kingdom
536981,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
538554,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom

In [17]:
df["Description"].isnull().sum()

np.int64(1454)

In [18]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [19]:
df["InvoiceDate"].dtype

dtype('<M8[us]')

In [20]:
df["TotalPrice"] = df["Quantity"] * df["UnitPrice"]

In [21]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'TotalPrice'],
      dtype='str')

In [22]:
df["Invoice Date"] = df["InvoiceDate"].dt.strftime("%y/%m/%d")
df["Invoice Time"]  = df["InvoiceDate"].dt.strftime("%H:%M:%S")
df.drop(columns=["InvoiceDate"], inplace = True)

In [23]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'UnitPrice',
       'CustomerID', 'Country', 'TotalPrice', 'Invoice Date', 'Invoice Time'],
      dtype='str')

In [24]:
df[df["Description"] != df["Description"].str.strip()]

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,TotalPrice,Invoice Date,Invoice Time
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2.10,13047.0,United Kingdom,12.60,10/12/01,08:34:00
13,536367,22310,IVORY KNITTED MUG COSY,6,1.65,13047.0,United Kingdom,9.90,10/12/01,08:34:00
15,536367,22623,BOX OF VINTAGE JIGSAW BLOCKS,3,4.95,13047.0,United Kingdom,14.85,10/12/01,08:34:00
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,3.75,12583.0,France,90.00,10/12/01,08:45:00
30,536370,21883,STARS GIFT TAPE,24,0.65,12583.0,France,15.60,10/12/01,08:45:00
...,...,...,...,...,...,...,...,...,...,...
541902,581587,22629,SPACEBOY LUNCH BOX,12,1.95,12680.0,France,23.40,11/12/09,12:50:00
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,4.15,12680.0,France,16.60,11/12/09,12:50:00
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2.10,12680.0,France,12.60,11/12/09,12:50:00
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,4.15,12680.0,France,16.60,11/12/09,12:50:00
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,4.95,12680.0,France,14.85,11/12/09,12:50:00

In [25]:
Top10Customers = df.sort_values("TotalPrice", ascending=False).head(10)
Top10Customers

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,TotalPrice,Invoice Date,Invoice Time
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,16446.0,United Kingdom,168469.60,11/12/09,09:15:00
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,12346.0,United Kingdom,77183.60,11/01/18,10:01:00
222680,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,649.50,15098.0,United Kingdom,38970.00,11/06/10,15:28:00
15017,537632,AMAZONFEE,AMAZON FEE,1,13541.33,NaN,United Kingdom,13541.33,10/12/07,15:08:00
299982,A563185,B,Adjust bad debt,1,11062.06,NaN,United Kingdom,11062.06,11/08/12,14:50:00
173382,551697,POST,POSTAGE,1,8142.75,16029.0,United Kingdom,8142.75,11/05/03,13:46:00
348325,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,5.06,17450.0,United Kingdom,7144.72,11/09/20,11:05:00
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,15749.0,United Kingdom,6539.40,11/04/18,13:20:00
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,15749.0,United Kingdom,6539.40,11/01/11,12:55:00
421601,573003,23084,RABBIT NIGHT LIGHT,2400,2.08,14646.0,Netherlands,4992.00,11/10/27,12:11:00

In [26]:
df = df.dropna(how = "all")

In [27]:
df.isnull().sum().sum()

np.int64(136534)

In [28]:
#Monthly Revenue

df["Month"] = pd.to_datetime(df["Invoice Date"]).dt.to_period("M")
monthly_sales = df.groupby("Month")["TotalPrice"].sum().sort_values(ascending=False)

C:\Users\Abdul Rehman\AppData\Local\Temp\ipykernel_12340\1124086254.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Month"] = pd.to_datetime(df["Invoice Date"]).dt.to_period("M")

In [29]:
df = df.drop_duplicates()

In [30]:
df.duplicated().sum().sum()

np.int64(0)

In [31]:
Transactionspercountry = df["Country"].value_counts()

In [32]:
top_products_revenue = df.groupby("Description")["TotalPrice"].sum().sort_values(ascending=False).head(10)

In [33]:
top_products_quantity = df.groupby("Description")["Quantity"].sum().sort_values(ascending=False).head(10)

In [34]:
country_revenue = df.groupby("Country")["TotalPrice"].sum().sort_values(ascending=False)

In [35]:
total_revenue = df["TotalPrice"].sum()
total_orders = df["InvoiceNo"].nunique()
average_order_value = total_revenue / total_orders
average_order_value

np.float64(375.521504015444)

In [36]:
customer_orders = df.groupby("CustomerID")["InvoiceNo"].nunique().sort_values(ascending=False)
customer_orders.head(10)

CustomerID
14911.0    248
12748.0    224
17841.0    169
14606.0    128
13089.0    118
15311.0    118
12971.0     89
14527.0     86
13408.0     81
14646.0     77
Name: InvoiceNo, dtype: int64

In [37]:
customer_orders = df.groupby("CustomerID")["InvoiceNo"].nunique()
repeat_customers = customer_orders[customer_orders > 1]
repeat_customers

CustomerID
12346.0     2
12347.0     7
12348.0     4
12352.0    11
12356.0     3
           ..
18276.0     3
18277.0     2
18282.0     3
18283.0    16
18287.0     3
Name: InvoiceNo, Length: 3059, dtype: int64

In [38]:
repeat_customers.count()

np.int64(3059)

In [39]:
one_time_customers = customer_orders[customer_orders == 1]
one_time_customers.count()

np.int64(1313)

In [40]:
customer_spending = df.groupby("CustomerID")["TotalPrice"].sum().sort_values(ascending=False)
customer_spending.head(10)

CustomerID
14646.0    279489.02
18102.0    256438.49
17450.0    187322.17
14911.0    132458.73
12415.0    123725.45
14156.0    113214.59
17511.0     88125.38
16684.0     65892.08
13694.0     62690.54
15311.0     59284.19
Name: TotalPrice, dtype: float64

In [41]:
customer_spending = df.groupby("CustomerID")["TotalPrice"].sum()
high_value = customer_spending[customer_spending >= 5000]
medium_value = customer_spending[
    (customer_spending >= 1000) &
    (customer_spending < 5000)
]
low_value = customer_spending[customer_spending < 1000]

In [42]:
print("High Value:", len(high_value))
print("Medium Value:", len(medium_value))
print("Low Value:", len(low_value))

High Value: 262
Medium Value: 1368
Low Value: 2742

In [43]:
country_analysis = df.groupby("Country").agg(
    Revenue=("TotalPrice", "sum"),
    Orders=("InvoiceNo", "nunique")
)
country_analysis["Average_Order_Value"] = (
    country_analysis["Revenue"] / country_analysis["Orders"]
)
country_analysis = country_analysis.sort_values(
    "Revenue", ascending=False
)
country_analysis

                          Revenue  Orders  Average_Order_Value
Country
United Kingdom        8167128.184   23494           347.626125
Netherlands            284661.540     101          2818.431089
EIRE                   262993.380     360           730.537167
Germany                221509.470     603           367.345721
France                 197317.110     461           428.019761
Australia              137009.770      69          1985.648841
Switzerland             56363.050      74           761.662838
Spain                   54756.030     105           521.486000
Belgium                 40910.960     119           343.789580
Sweden                  36585.410      46           795.335000
Japan                   35340.620      28          1262.165000
Norway                  35163.460      40           879.086500
Portugal                29302.970      71           412.717887
Finland                 22326.740      48           465.140417
Channel Islands         20076.390      33           608.375455
Denmark                 18768.140      21           893.720952
Italy                   16890.510      55           307.100182
Cyprus                  12858.760      20           642.938000
Austria                 10154.320      19           534.437895
Hong Kong                9908.240      15           660.549333
Singapore                9120.390      10           912.039000
Israel                   7901.970       9           877.996667
Poland                   7213.140      24           300.547500
Unspecified              4740.940      13           364.687692
Greece                   4710.520       6           785.086667
Iceland                  4310.000       7           615.714286
Canada                   3666.380       6           611.063333
Malta                    2505.470      10           250.547000
United Arab Emirates     1902.280       3           634.093333
USA                      1730.920       7           247.274286
Lebanon                  1693.880       1          1693.880000
Lithuania                1661.060       4           415.265000
European Community       1291.750       5           258.350000
Brazil                   1143.600       1          1143.600000
RSA                      1002.310       1          1002.310000
Czech Republic            707.720       5           141.544000
Bahrain                   548.400       4           137.100000
Saudi Arabia              131.170       2            65.585000

In [44]:
product_analysis = df.groupby("Description").agg(
    Revenue=("TotalPrice", "sum"),
    Orders=("InvoiceNo", "nunique")
)
product_analysis = product_analysis.sort_values(
    "Revenue", ascending=False
)
product_analysis.head(10)

                                      Revenue  Orders
Description
DOTCOM POSTAGE                      206245.48     709
REGENCY CAKESTAND 3 TIER            164459.49    2169
WHITE HANGING HEART T-LIGHT HOLDER   99612.42    2302
PARTY BUNTING                        98243.88    1706
JUMBO BAG RED RETROSPOT              92175.79    2135
RABBIT NIGHT LIGHT                   66661.63    1009
POSTAGE                              66230.64    1250
PAPER CHAIN KIT 50'S CHRISTMAS       63715.24    1170
ASSORTED COLOUR BIRD ORNAMENT        58792.42    1467
CHILLI LIGHTS                        53746.66     669

In [45]:
High_value_transactions = df.sort_values("TotalPrice", ascending=False).head(10)
High_value_transactions

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,TotalPrice,Invoice Date,Invoice Time,Month
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,16446.0,United Kingdom,168469.60,11/12/09,09:15:00,2009-11
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,12346.0,United Kingdom,77183.60,11/01/18,10:01:00,2018-11
222680,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,649.50,15098.0,United Kingdom,38970.00,11/06/10,15:28:00,2010-11
15017,537632,AMAZONFEE,AMAZON FEE,1,13541.33,NaN,United Kingdom,13541.33,10/12/07,15:08:00,2007-10
299982,A563185,B,Adjust bad debt,1,11062.06,NaN,United Kingdom,11062.06,11/08/12,14:50:00,2012-11
173382,551697,POST,POSTAGE,1,8142.75,16029.0,United Kingdom,8142.75,11/05/03,13:46:00,2003-11
348325,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,5.06,17450.0,United Kingdom,7144.72,11/09/20,11:05:00,2020-11
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,15749.0,United Kingdom,6539.40,11/04/18,13:20:00,2018-11
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2.10,15749.0,United Kingdom,6539.40,11/01/11,12:55:00,2011-11
421601,573003,23084,RABBIT NIGHT LIGHT,2400,2.08,14646.0,Netherlands,4992.00,11/10/27,12:11:00,2027-11

In [46]:
df["Year"] = pd.to_datetime(df["Invoice Date"]).dt.year
yearly_revenue = df.groupby("Year")["TotalPrice"].sum()
yearly_revenue

C:\Users\Abdul Rehman\AppData\Local\Temp\ipykernel_12340\1000977206.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Year"] = pd.to_datetime(df["Invoice Date"]).dt.year

Year
2001    315451.460
2002    287886.080
2003    307576.200
2004    366126.580
2005    342514.510
2006    379816.500
2007    449035.540
2008    385662.940
2009    340104.210
2010    343928.830
2011    390313.010
2012    232288.630
2013    276867.680
2014    425652.700
2015    325955.321
2016    290463.180
2017    398068.060
2018    307295.330
2019    262012.470
2020    393127.750
2021    372250.670
2022    282499.150
2023    283095.250
2024    279104.070
2025    271859.301
2026    202211.912
2027    238730.800
2028    319617.710
2029    232893.660
2030    250626.530
2031    172970.920
Name: TotalPrice, dtype: float64

In [47]:
df["Hour"] = pd.to_datetime(df["Invoice Time"].astype(str)).dt.hour
hourly_sales = df.groupby("Hour")["TotalPrice"].sum().sort_values(ascending=False)
hourly_sales

C:\Users\Abdul Rehman\AppData\Local\Temp\ipykernel_12340\123353947.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Hour"] = pd.to_datetime(df["Invoice Time"].astype(str)).dt.hour

Hour
12    1357595.120
10    1327329.891
15    1186819.410
13    1172985.870
11    1146457.490
14    1091408.741
9      766524.171
16     727666.670
17     434834.541
8      281723.020
18     140365.040
19      45864.930
7       31009.320
20      15920.090
6        -497.350
Name: TotalPrice, dtype: float64

In [48]:
cancelled_df = df[df["InvoiceNo"].astype(str).str.startswith("C")]

In [49]:
df = df[~df["InvoiceNo"].astype(str).str.startswith("C")]

In [50]:
print(len(df))
print(len(cancelled_df))
print(len(df))

527390
9251
527390

In [51]:
df[df["InvoiceNo"].astype(str).str.startswith("C")]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, UnitPrice, CustomerID, Country, TotalPrice, Invoice Date, Invoice Time, Month, Year, Hour]
Index: []

In [52]:
print(df[df["InvoiceNo"].astype(str).str.startswith("C")])

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, UnitPrice, CustomerID, Country, TotalPrice, Invoice Date, Invoice Time, Month, Year, Hour]
Index: []

In [53]:
cancellations_per_country = cancelled_df.groupby("Country")["InvoiceNo"].count().sort_values(ascending=False)
cancellations_per_country

Country
United Kingdom        7821
Germany                453
EIRE                   301
France                 148
USA                    112
Australia               74
Spain                   48
Italy                   45
Belgium                 38
Japan                   37
Switzerland             35
Portugal                18
Malta                   15
Norway                  14
Sweden                  11
Poland                  11
Finland                 10
Channel Islands         10
Denmark                  9
Cyprus                   8
Netherlands              8
Singapore                7
Czech Republic           5
Hong Kong                4
Austria                  3
Israel                   2
Saudi Arabia             1
Greece                   1
European Community       1
Bahrain                  1
Name: InvoiceNo, dtype: int64

In [54]:
top10_cancellation_countries = cancelled_df.groupby("Country")["InvoiceNo"].count().sort_values(ascending=False).head(10)
top10_cancellation_countries

Country
United Kingdom    7821
Germany            453
EIRE               301
France             148
USA                112
Australia           74
Spain               48
Italy               45
Belgium             38
Japan               37
Name: InvoiceNo, dtype: int64

In [55]:
df.dtypes

InvoiceNo             str
StockCode             str
Description           str
Quantity            int64
UnitPrice         float64
CustomerID        float64
Country               str
TotalPrice        float64
Invoice Date          str
Invoice Time          str
Month           period[M]
Year                int32
Hour                int32
dtype: object

In [56]:
text_columns = [ "StockCode", "Description", "Country",]

df[text_columns] = df[text_columns].apply(lambda x: x.str.title())

In [57]:
total_revenue = df["TotalPrice"].sum()

total_orders = df["InvoiceNo"].nunique()

total_customers = df["CustomerID"].nunique()

total_products = df["Description"].nunique()

total_quantity = df["Quantity"].sum()

average_order_value = total_revenue / total_orders

In [58]:
summary_dashboard = pd.DataFrame({
    "KPI": [
        "Total Revenue",
        "Total Orders",
        "Total Customers",
        "Total Products",
        "Total Quantity Sold",
        "Average Order Value"
    ],
    "Value": [
        total_revenue,
        total_orders,
        total_customers,
        total_products,
        total_quantity,
        average_order_value
    ]
})

In [59]:
summary_dashboard

                   KPI         Value
0        Total Revenue  1.061999e+07
1         Total Orders  2.206400e+04
2      Total Customers  4.339000e+03
3       Total Products  4.190000e+03
4  Total Quantity Sold  5.438062e+06
5  Average Order Value  4.813264e+02

In [ ]:
#Monthly Revenue

df["Month"] = pd.to_datetime(df["Invoice Date"]).dt.to_period("M")
monthly_sales = df.groupby("Month")["TotalPrice"].sum().sort_values(ascending=False)

C:\Users\Abdul Rehman\AppData\Local\Temp\ipykernel_5080\1124086254.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Month"] = pd.to_datetime(df["Invoice Date"]).dt.to_period("M")

In [64]:
def check_dtype(var, label):
    print(f"\n=== {label} ===")
    print("Type:", type(var))
    if isinstance(var, pd.Series):
        print("dtype:", var.dtype)
    elif isinstance(var, pd.DataFrame):
        print(var.dtypes)
    else:
        print("Not a Series or DataFrame")

check_dtype(summary_dashboard, "summary_dashboard")
check_dtype(df, "df")
check_dtype(Top10Customers, "Top10Customers")
check_dtype(total_revenue, "total_revenue")
check_dtype(total_orders, "total_orders")
check_dtype(top_products_revenue, "top_products_revenue")
check_dtype(top_products_quantity, "top_products_quantity")
check_dtype(Transactionspercountry, "Transactionspercountry")
check_dtype(High_value_transactions, "High_value_transactions")
check_dtype(country_revenue, "country_revenue")
check_dtype(average_order_value, "average_order_value")
check_dtype(country_analysis, "country_analysis")
check_dtype(product_analysis, "product_analysis")
check_dtype(customer_orders, "customer_orders")
check_dtype(customer_spending, "customer_spending")
check_dtype(repeat_customers, "repeat_customers")
check_dtype(one_time_customers, "one_time_customers")
check_dtype(hourly_sales, "hourly_sales")
check_dtype(monthly_sales, "monthly_sales")
check_dtype(yearly_revenue, "yearly_revenue")
check_dtype(cancellations_per_country, "cancellations_per_country")
check_dtype(top10_cancellation_countries, "top10_cancellation_countries")

=== summary_dashboard ===
Type: <class 'pandas.DataFrame'>
KPI          str
Value    float64
dtype: object

=== df ===
Type: <class 'pandas.DataFrame'>
InvoiceNo             str
StockCode             str
Description           str
Quantity            int64
UnitPrice         float64
CustomerID        float64
Country               str
TotalPrice        float64
Invoice Date          str
Invoice Time          str
Month           period[M]
Year                int32
Hour                int32
dtype: object

=== Top10Customers ===
Type: <class 'pandas.DataFrame'>
InvoiceNo           str
StockCode           str
Description         str
Quantity          int64
UnitPrice       float64
CustomerID      float64
Country             str
TotalPrice      float64
Invoice Date        str
Invoice Time        str
dtype: object

=== total_revenue ===
Type: <class 'numpy.float64'>
Not a Series or DataFrame

=== total_orders ===
Type: <class 'int'>
Not a Series or DataFrame

=== top_products_revenue ===
Type: <class 'pandas.Series'>
dtype: float64

=== top_products_quantity ===
Type: <class 'pandas.Series'>
dtype: int64

=== Transactionspercountry ===
Type: <class 'pandas.Series'>
dtype: int64

=== High_value_transactions ===
Type: <class 'pandas.DataFrame'>
InvoiceNo             str
StockCode             str
Description           str
Quantity            int64
UnitPrice         float64
CustomerID        float64
Country               str
TotalPrice        float64
Invoice Date          str
Invoice Time          str
Month           period[M]
dtype: object

=== country_revenue ===
Type: <class 'pandas.Series'>
dtype: float64

=== average_order_value ===
Type: <class 'numpy.float64'>
Not a Series or DataFrame

=== country_analysis ===
Type: <class 'pandas.DataFrame'>
Revenue                float64
Orders                   int64
Average_Order_Value    float64
dtype: object

=== product_analysis ===
Type: <class 'pandas.DataFrame'>
Revenue    float64
Orders       int64
dtype: object

=== customer_orders ===
Type: <class 'pandas.Series'>
dtype: int64

=== customer_spending ===
Type: <class 'pandas.Series'>
dtype: float64

=== repeat_customers ===
Type: <class 'pandas.Series'>
dtype: int64

=== one_time_customers ===
Type: <class 'pandas.Series'>
dtype: int64

=== hourly_sales ===
Type: <class 'pandas.Series'>
dtype: float64

=== monthly_sales ===
Type: <class 'pandas.Series'>
dtype: float64

=== yearly_revenue ===
Type: <class 'pandas.Series'>
dtype: float64

=== cancellations_per_country ===
Type: <class 'pandas.Series'>
dtype: int64

=== top10_cancellation_countries ===
Type: <class 'pandas.Series'>
dtype: int64

In [60]:
with pd.ExcelWriter("Retail_Analysis_Report.xlsx", engine="openpyxl") as writer:

    summary_dashboard.to_excel(writer, sheet_name="Summary Dashboard", index=False)
    df.to_excel(writer, sheet_name="Cleaned Data", index=False)
    Top10Customers.to_excel(writer, sheet_name="Top 10 Customers")
    total_revenue.to_excel(writer, sheet_name="Total Revenue")
    total_orders.to_excel(writer, sheet_name="Total Orders")
    top_products_revenue.to_excel(writer, sheet_name="Top Products Revenue")
    top_products_quantity.to_excel(writer, sheet_name="Top Products Quantity")
    Transactionspercountry.to_excel(writer, sheet_name= "Transactions per country")
    High_value_transactions.to_excel(writer, sheet_name="High Value Transactions")
    country_revenue.to_excel(writer, sheet_name= "Revenue per Country")
    average_order_value.to_excel(writer, sheet_name="Average Order Value")
    country_analysis.to_excel(writer, sheet_name="Country Analysis")
    product_analysis.to_excel(writer, sheet_name="Product Analysis")
    customer_orders.to_excel(writer, sheet_name="Customer Orders")
    customer_spending.to_excel(writer, sheet_name="Customer Spending")
    repeat_customers.to_excel(writer, sheet_name="Repeat Customers")
    one_time_customers.to_excel(writer, sheet_name="One Time Customers")
    hourly_sales.to_excel(writer, sheet_name="Hourly Sales")
    monthly_sales.to_excel(writer, sheet_name="Monthly Sales")
    yearly_revenue.to_excel(writer, sheet_name="Annual Revenue")
    cancellations_per_country.to_excel(writer, sheet_name="Cancellation per Country")
    top10_cancellation_countries.to_excel(writer, sheet_name="Top 10 Cancellations")


print("Excel report created successfully!")

AttributeError: 'numpy.float64' object has no attribute 'to_excel'